### ISSUE TITLE
Add <link> with rel="alternate" to event Atom XML

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-major-event-log#38]
In the event Atom XML we should add a `<link>` element with rel="alternate" that links to the HTML version of the event. For example, if we have an event here:
http://.../major-event-log/event/c7dc0058-99b9-482e-8f71-1f463d2295a9.xml
we would have a link:
`<link href="http://.../major-event-log/event/c7dc0058-99b9-482e-8f71-1f463d2295a9/" rel="alternate"/>`.

**Comment by somexpert** [comment]
And this link, where exactly will it appear? The Atom items in the feed at /feed/, the Atom items at /event/[event_id].xml, or both?

**Comment by ldko** [comment]
The items in the feed should already have that link. It should be added to /event/[event_id].xml.

**Comment by somexpert** [comment]
Closed by fix-xml branch merge.
