### ISSUE TITLE
Would using the django-major-event-log app satisfy HIPAA's event logging requirements?

### ISSUE THREAD

**Issue by DanielStevenLewis** [unt-libraries/django-major-event-log#45]
I'm trying to figure out the easiest way to implement event logging with Django so as to meet HIPAA's event logging requirements. Would using https://github.com/unt-libraries/django-major-event-log to log major events in Premis format (at least help to) satisfy these requirements?
http://programmers.stackexchange.com/questions/291713/would-using-the-django-major-event-log-app-satisfy-hipaas-event-logging-require

**Comment by somexpert** [comment]
First, thank you for the interest! I will do my best to address your question. Unfortunately, I am wholly unfamiliar with any of the HIPAA standards or requirements. It might be the case that the "events" that are referred to in this application are completely different from the ones you are trying to log. The "events" in this app refer to [PREMIS](http://www.loc.gov/standards/premis/) events, and may not be very adaptable to suit your needs. As such, I cannot give you a solid answer. The type of events that we will be logging with this app include events that occur within our infrastructure that relate to all or a large portion of the digital objects in our repository and for which it is desirable to keep a record that an event occurred that affected them.
