### ISSUE TITLE
test against py37

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-major-event-log#53]
We can add testing against Python 3.7 to make sure it works and at the same time remove testing against Django versions that are no longer available in Travis.

**Comment by madhuBayy** [comment]
The minimum version of lxml required for py37 is 4.2.2 but this isn't supported by py34 . Do you think support for py34 can be removed?

**Comment by ldko** [comment]
Yes, I think it is ok to remove support for Python 3.4 on any of our projects because it went end of life in March.

**Comment by ldko** [comment]
Done in #54.
